# ============================================================================
#  MANAGED FILE - DO NOT EDIT IN THE CUSTOMER WORKSPACE
#  Source: Templates\customer-repo\.claude\hooks\deny-system-edits.ps1 inside
#          the NKDAgility.AzureDevOps.AutomationTools module.
# ============================================================================
<#
.SYNOPSIS
    PreToolUse hook: refuses any write into .system\.

.DESCRIPTION
    .system\ holds engine code copied in by init.ps1. It is regenerated on every
    run, so an edit there is destroyed without trace - the change has to go into
    the tools clone instead.

    Three things guard that folder, and this is the one that catches agents:
      1. the files are marked read-only when they are copied,
      2. init.ps1 stops if it notices .system\ has changed since it was written,
      3. this hook blocks the write before it happens.

    Claude Code passes the tool call as JSON on stdin. Exit code 2 blocks the
    call and returns stderr to the model as the reason.
#>
$ErrorActionPreference = 'Stop'

try {
    $payload = [Console]::In.ReadToEnd() | ConvertFrom-Json
}
catch {
    # A hook that cannot parse its input must not block real work.
    exit 0
}

$path = $payload.tool_input.file_path
if (-not $path) { exit 0 }

if ($path -match '[\\/]\.system[\\/]') {
    [Console]::Error.Write(
        "Refused: '$path' is inside .system\, which is generated by init.ps1 and " +
        "overwritten on every run - this edit would be lost. Make the change in the " +
        "tools clone (%USERPROFILE%\source\repos\azure-devops-automation-tools, or " +
        "the toolsPath in workspace.local.json) and re-run '. .\init.ps1' to copy it in."
    )
    exit 2
}

exit 0
